FROM kalilinux/kali-rolling

RUN apt update --error-on=any \
    && apt install -y --no-install-recommends \
    time curl git nano \
    net-tools iputils-ping iproute2 sudo gdb less \
    python3 python3-pip python3-venv python-is-python3 \
    dsniff tcpdump iptables\
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN python -m pip install --no-cache-dir --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN python -m pip install --no-cache-dir -r /tmp/requirements.txt
