services:
  notebook:
    build:
      context: ./ # Use the current directory as the build context
      dockerfile: Dockerfile.kali
    image: kali
    privileged: true
    container_name: kali
    hostname: kali
    working_dir: /course_contents
    cap_add:
      - ALL
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./:/course_contents
    ports:
      - 8888:8888
    networks:
      net-192.168.100.0:
        ipv4_address: 192.168.100.10
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "jupyter notebook --allow-root --ip=192.168.100.10 --port=8888",
      ]

  server:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: server
    container_name: server
    hostname: server
    tty: true
    cap_add:
      - ALL
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./course/demos/FlaskWebApp:/app
    ports:
      - 5555:5555
    privileged: true
    sysctls:
      - net.ipv4.tcp_syncookies=0
      - net.ipv4.tcp_max_syn_backlog=1
      - net.ipv4.tcp_synack_retries=100
    networks:
      net-192.168.100.0:
        ipv4_address: 192.168.100.200

  client:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: lab-client
    container_name: client
    hostname: client
    tty: true
    networks:
      net-192.168.100.0:
        ipv4_address: 192.168.100.100

networks:
  net-192.168.100.0:
    name: net-192.168.100.0
    ipam:
      config:
        - subnet: 192.168.100.0/24
