version: "3"

services:
  router:
    image: handsonsecurity/seed-ubuntu:large
    container_name: router-11
    hostname: router-11
    tty: true
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.11
      net-10.8.0.0:
        ipv4_address: 10.8.0.11
    command: bash -c "
      ip route del default  &&
      ip route add default via 10.8.0.1 &&
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      tail -f /dev/null"

  dns-server:
    build: ./dns_server
    image: dns-server
    container_name: dns-server-53
    hostname: dns-server-53
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.53
    command: bash -c "
      ip route del default  &&
      ip route add default via 10.9.0.11 &&
      service named start && tail -f /dev/null"

  user:
    build: ./user
    image: user
    container_name: user-5
    hostname: user-5
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    command: bash -c "
      ip route del default  &&
      ip route add default via 10.9.0.11 &&
      /start.sh"

  attacker:
    image: handsonsecurity/seed-ubuntu:large
    container_name: attacker
    hostname: attacker
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    network_mode: host

  attackers-ns:
    build: ./attackers_ns
    image: attackers-ns
    container_name: attackers-ns-153
    hostname: attackers-ns-153
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.153

  firefox:
    image: jlesage/firefox
    container_name: firefox
    hostname: firefox
    restart: always
    cap_add:
      - ALL
    ports:
      - "5800:5800"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.100
    dns:
      - 10.9.0.53

networks:
  net-10.8.0.0:
    name: net-10.8.0.0
    ipam:
      config:
        - subnet: 10.8.0.0/24

  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
